apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud
  labels:
    app: go-crud
spec:
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-crud
  template:
    metadata:
      labels:
        app: go-crud
    spec:
      restartPolicy: Always
      containers:
      - name: go-crud
        image: meziaris/go-crud:latest
        imagePullPolicy: Always
        ports:
          - name: app-port
            containerPort: 8080
        resources:
          requests:
            cpu: "0.1"
            memory: "100Mi"
        securityContext:
          runAsUser: 1000
        envFrom:
        - secretRef:
            name: go-crud-secret-env
        volumeMounts:
        - name: tz-jakarta
          mountPath: /etc/localtime
      volumes:
        - name: tz-jakarta
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta
