apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-crud
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - go.api.mezi.dev
    secretName: go-crud-tls
  rules:
  - host: go.api.mezi.dev
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: go-crud
            port:
              number: 80
