version: "3.9" # optional since v1.27.0
services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    healthcheck:
      test: cho 'db.runCommand("ping").ok' | mongo localhost:27017/go-crud --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: go-crud
    networks:
      go-crud:
        ipv4_address: 172.27.1.1
        aliases:
          - mongo
  go-crud:
    container_name: go-crud
    image: meziaris/go-crud
    env_file:
      - ../../.env
    ports:
      - 8080:8080
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      go-crud:
        ipv4_address: 172.27.1.2
        aliases:
          - go-crud

networks:
  go-crud:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
